/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auth Status */
        get: operations["get_auth_status_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Token */
        post: operations["get_token_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create summarize job */
        post: operations["create_summarize_job_api_v1_jobs_summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List summarized URLs (grouped, home page) */
        get: operations["list_summarized_urls_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all jobs flat (/jobs page) */
        get: operations["list_all_jobs_flat_api_v1_jobs_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/by-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all jobs for a URL */
        get: operations["get_jobs_for_url_api_v1_jobs_by_url_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get job status (polling) */
        get: operations["get_job_status_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get supported models */
        get: operations["get_supported_models_api_v1_meta_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get supported languages */
        get: operations["get_supported_languages_api_v1_meta_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get supported summary modes
         * @description Returns {mode_key: human_readable_label}.
         */
        get: operations["get_supported_modes_api_v1_meta_modes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the build this backend was deployed from */
        get: operations["get_version_api_v1_meta_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/keepalive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hold a connection open while background work runs
         * @description Held open for as long as there is background work, up to a bounded window.
         *
         *     Cloud Run may reclaim an instance that has no request in flight. Summarisation and
         *     evaluation both run as background tasks after their response was already sent, so this
         *     open connection is what keeps the instance carrying them alive.
         *
         *     Returns as soon as the work finishes, so callers loop on `active_work > 0` and an idle
         *     caller cannot pin an instance.
         */
        get: operations["keepalive_api_v1_meta_keepalive_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/evaluation-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluation Sets */
        get: operations["list_evaluation_sets_api_v1_research_evaluation_sets_get"];
        put?: never;
        /** Create Evaluation Set */
        post: operations["create_evaluation_set_api_v1_research_evaluation_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/evaluation-sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Set */
        get: operations["get_evaluation_set_api_v1_research_evaluation_sets__set_id__get"];
        put?: never;
        post?: never;
        /** Delete Evaluation Set */
        delete: operations["delete_evaluation_set_api_v1_research_evaluation_sets__set_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/evaluation-sets/{set_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Evaluation Set */
        get: operations["export_evaluation_set_api_v1_research_evaluation_sets__set_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/evaluation-sets/{set_id}/entries/{entry_id}/input-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Set Entry Input Text */
        get: operations["get_evaluation_set_entry_input_text_api_v1_research_evaluation_sets__set_id__entries__entry_id__input_text_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/evaluation-sets/{set_id}/golden-metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Missing Golden Metrics */
        post: operations["evaluate_missing_golden_metrics_api_v1_research_evaluation_sets__set_id__golden_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/evaluation-sets/{set_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluation Runs */
        get: operations["list_evaluation_runs_api_v1_research_evaluation_sets__set_id__runs_get"];
        put?: never;
        /** Create Evaluation Run */
        post: operations["create_evaluation_run_api_v1_research_evaluation_sets__set_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Run */
        get: operations["get_evaluation_run_api_v1_research_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Delete Evaluation Run */
        delete: operations["delete_evaluation_run_api_v1_research_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/runs/{run_id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evaluation Run Entries */
        get: operations["get_evaluation_run_entries_api_v1_research_runs__run_id__entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/runs/{run_id}/deepeval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate Run Deepeval */
        post: operations["evaluate_run_deepeval_api_v1_research_runs__run_id__deepeval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Evaluation Run */
        post: operations["resume_evaluation_run_api_v1_research_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiMetrics */
        AiMetrics: {
            summary: components["schemas"]["SummaryStatisticalMetrics"];
            key_takeaways: components["schemas"]["KeyTakeawaysMetrics"];
            /** Deepeval */
            deepeval: components["schemas"]["DeepevalItem"][] | null;
        };
        /** AuthStatusResponse */
        AuthStatusResponse: {
            /** Enabled */
            enabled: boolean;
        };
        /** CrossMetrics */
        CrossMetrics: {
            /** Rouge1 */
            rouge1: number;
            /** Rouge2 */
            rouge2: number;
            /** Rougel */
            rougeL: number;
            /** Meteor */
            meteor: number;
            /** Deepeval */
            deepeval: components["schemas"]["PairwiseDeepevalItem"][];
        };
        /** DeepevalItem */
        DeepevalItem: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Passed */
            passed: boolean;
            /** Reason */
            reason: string;
        };
        /**
         * DeepevalPassMetrics
         * @description Progress of the GEval pass, which runs separately from the run itself.
         */
        DeepevalPassMetrics: {
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed";
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Updated Entries */
            updated_entries: number | null;
            /** Skipped Entries */
            skipped_entries: number | null;
            /** Already Scored Entries */
            already_scored_entries: number | null;
            /** Error */
            error: string | null;
        };
        /** DeepevalQueuedResponse */
        DeepevalQueuedResponse: {
            /**
             * Status
             * @constant
             */
            status: "queued";
            /** Run Id */
            run_id: string;
        };
        /** EvaluationRunAggregateMetrics */
        EvaluationRunAggregateMetrics: {
            /** Entry Count */
            entry_count: number | null;
            /** Completed Entries */
            completed_entries: number | null;
            /** Failed Entries */
            failed_entries: number | null;
            /** Error */
            error: string | null;
            deepeval: components["schemas"]["DeepevalPassMetrics"] | null;
        };
        /** EvaluationRunCreateRequest */
        EvaluationRunCreateRequest: {
            /** Model Provider */
            model_provider: string;
            /** Model Name */
            model_name: string;
            /**
             * Summary Mode
             * @default simple
             */
            summary_mode: string;
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Rate Limit Delay Ms
             * @default 0
             */
            rate_limit_delay_ms: number;
            /**
             * Skip Takeaways
             * @default false
             */
            skip_takeaways: boolean;
        };
        /** EvaluationRunCreateResponse */
        EvaluationRunCreateResponse: {
            /** Evaluation Run Id */
            evaluation_run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvaluationRunDeletedResponse */
        EvaluationRunDeletedResponse: {
            /**
             * Status
             * @constant
             */
            status: "deleted";
            /** Evaluation Run Id */
            evaluation_run_id: string;
        };
        /** EvaluationRunEntriesResponse */
        EvaluationRunEntriesResponse: {
            /** Entries */
            entries: components["schemas"]["EvaluationRunEntryResponse"][];
        };
        /**
         * EvaluationRunEntryResponse
         * @description API-facing shape — includes title/url/golden_metrics joined from the parent set.
         */
        EvaluationRunEntryResponse: {
            /** Entry Id */
            entry_id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Golden Summary */
            golden_summary: string;
            golden_metrics: components["schemas"]["GoldenMetrics"] | null;
            /** Ai Summary */
            ai_summary: string | null;
            /** Ai Key Takeaways */
            ai_key_takeaways: string[];
            ai_metrics: components["schemas"]["AiMetrics"] | null;
            cross_metrics: components["schemas"]["CrossMetrics"] | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /** Error */
            error: string | null;
        };
        /** EvaluationRunListItemResponse */
        EvaluationRunListItemResponse: {
            /** Evaluation Run Id */
            evaluation_run_id: string;
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Evaluation Set Name */
            evaluation_set_name: string;
            /** Model Provider */
            model_provider: string;
            /** Model Name */
            model_name: string;
            /** Summary Mode */
            summary_mode: string;
            /** Language */
            language: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Entry Count */
            entry_count: number;
        };
        /** EvaluationRunResponse */
        EvaluationRunResponse: {
            /** Id */
            id: string;
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Evaluation Set Name */
            evaluation_set_name: string;
            /** Model Provider */
            model_provider: string;
            /** Model Name */
            model_name: string;
            /** Summary Mode */
            summary_mode: string;
            /** Language */
            language: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Entry Count */
            entry_count: number;
            /** Skip Takeaways */
            skip_takeaways: boolean;
            aggregate_metrics: components["schemas"]["EvaluationRunAggregateMetrics"];
        };
        /** EvaluationRunResumeResponse */
        EvaluationRunResumeResponse: {
            /**
             * Status
             * @constant
             */
            status: "queued";
            /** Evaluation Run Id */
            evaluation_run_id: string;
            /** Resume Attempts */
            resume_attempts: number;
        };
        /** EvaluationSetCreateResponse */
        EvaluationSetCreateResponse: {
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Name */
            name: string;
            /** Language */
            language: string;
            /** Entry Count */
            entry_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvaluationSetDeletedResponse */
        EvaluationSetDeletedResponse: {
            /**
             * Status
             * @constant
             */
            status: "deleted";
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Deleted Runs */
            deleted_runs: number;
        };
        /** EvaluationSetDetailResponse */
        EvaluationSetDetailResponse: {
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Name */
            name: string;
            /** Language */
            language: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Entries */
            entries: components["schemas"]["EvaluationSetEntryResponse"][];
        };
        /** EvaluationSetEntryImport */
        "EvaluationSetEntryImport-Input": {
            /** Input Text */
            input_text: string;
            /** Golden Summary */
            golden_summary: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            golden_metrics?: components["schemas"]["GoldenMetrics"] | null;
        };
        /** EvaluationSetEntryImport */
        "EvaluationSetEntryImport-Output": {
            /** Input Text */
            input_text: string;
            /** Golden Summary */
            golden_summary: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            golden_metrics: components["schemas"]["GoldenMetrics"] | null;
        };
        /** EvaluationSetEntryInputTextResponse */
        EvaluationSetEntryInputTextResponse: {
            /** Entry Id */
            entry_id: string;
            /** Input Text */
            input_text: string;
        };
        /**
         * EvaluationSetEntryResponse
         * @description input_text is deliberately excluded — fetched separately via the input-text endpoint.
         */
        EvaluationSetEntryResponse: {
            /** Entry Id */
            entry_id: string;
            /** Golden Summary */
            golden_summary: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            golden_metrics: components["schemas"]["GoldenMetrics"] | null;
        };
        /**
         * EvaluationSetExportResponse
         * @description Mirrors EvaluationSetImportRequest so an exported file can be imported back.
         */
        EvaluationSetExportResponse: {
            /** Name */
            name: string;
            /** Language */
            language: string;
            /** Entries */
            entries: components["schemas"]["EvaluationSetEntryImport-Output"][];
        };
        /** EvaluationSetImportRequest */
        EvaluationSetImportRequest: {
            /** Name */
            name: string;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Entries */
            entries: components["schemas"]["EvaluationSetEntryImport-Input"][];
        };
        /** EvaluationSetListItemResponse */
        EvaluationSetListItemResponse: {
            /** Evaluation Set Id */
            evaluation_set_id: string;
            /** Name */
            name: string;
            /** Language */
            language: string;
            /** Entry Count */
            entry_count: number;
            /** Run Count */
            run_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** GoldenMetrics */
        GoldenMetrics: {
            source: components["schemas"]["SourceMetrics"];
            summary: components["schemas"]["SummaryStatisticalMetrics"];
            /** Deepeval */
            deepeval: components["schemas"]["DeepevalItem"][];
        };
        /** GoldenMetricsBackfillResponse */
        GoldenMetricsBackfillResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Updated Entries */
            updated_entries: number;
            /** Total Entries */
            total_entries: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Model Name */
            model_name: string;
            /** Model Provider */
            model_provider: string;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Summary Mode
             * @default simple
             * @enum {string}
             */
            summary_mode: "simple" | "sequential" | "cascade";
            /**
             * Run Deepeval
             * @default false
             */
            run_deepeval: boolean;
        };
        /** JobCreatedResponse */
        JobCreatedResponse: {
            /** Job Id */
            job_id: string;
        };
        /** JobDeletedResponse */
        JobDeletedResponse: {
            /**
             * Status
             * @constant
             */
            status: "deleted";
            /** Job Id */
            job_id: string;
        };
        /**
         * JobListItemResponse
         * @description Flat per-job entry used by GET /api/v1/jobs/list.
         */
        JobListItemResponse: {
            /** Job Id */
            job_id: string;
            /** Source Url */
            source_url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Model Provider */
            model_provider: string;
            /** Model Name */
            model_name: string;
            /**
             * Summary Mode
             * @enum {string}
             */
            summary_mode: "simple" | "sequential" | "cascade";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobMetrics
         * @description All None at insert time — metrics are computed asynchronously after the job starts.
         */
        JobMetrics: {
            source: components["schemas"]["SourceMetrics"] | null;
            summary: components["schemas"]["SummaryStatisticalMetrics"] | null;
            key_takeaways: components["schemas"]["KeyTakeawaysMetrics"] | null;
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /** Source Url */
            source_url: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /** Model Provider */
            model_provider: string;
            /** Model Name */
            model_name: string;
            /**
             * Summary Mode
             * @enum {string}
             */
            summary_mode: "simple" | "sequential" | "cascade";
            summary_data: components["schemas"]["SummaryResponse"] | null;
            metrics: components["schemas"]["JobMetrics"];
            /** Deepeval Metrics */
            deepeval_metrics: components["schemas"]["DeepevalItem"][];
            usage: components["schemas"]["UsageMetadata"];
            /** Raw Metadata */
            raw_metadata: {
                [key: string]: unknown;
            };
            /**
             * Raw Output
             * @default
             */
            raw_output: string;
            /**
             * Input Text
             * @default
             */
            input_text: string;
            /** Prompt Template */
            prompt_template: [
                string,
                string
            ][];
            /** Prompt Params */
            prompt_params: {
                [key: string]: string;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Duration Ms */
            duration_ms: number;
            /** Error */
            error: string | null;
        };
        /** KeepaliveResponse */
        KeepaliveResponse: {
            /** Active Work */
            active_work: number;
            /** Held Seconds */
            held_seconds: number;
        };
        /** KeyTakeawaysMetrics */
        KeyTakeawaysMetrics: {
            /** Bullet Count */
            bullet_count: number;
            /** Char Count */
            char_count: number;
        };
        /**
         * PairwiseDeepevalItem
         * @description score: raw GEval score, higher favors the AI summary (actual_output) over golden (expected_output).
         */
        PairwiseDeepevalItem: {
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Reason */
            reason: string;
        };
        /** SourceMetrics */
        SourceMetrics: {
            /** Char Count */
            char_count: number;
            /** Flesch Kincaid Grade */
            flesch_kincaid_grade: number;
        };
        /**
         * SummaryResponse
         * @description Structured output the LLM is asked to produce.
         */
        SummaryResponse: {
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Key Takeaways */
            key_takeaways: string[];
            /** Source Url */
            source_url: string;
        };
        /** SummaryStatisticalMetrics */
        SummaryStatisticalMetrics: {
            /** Char Count */
            char_count: number;
            /** Flesch Kincaid Grade */
            flesch_kincaid_grade: number;
            /** Length Ratio */
            length_ratio: number;
        };
        /** TokenRequest */
        TokenRequest: {
            /** Password */
            password: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Token */
            token: string;
        };
        /**
         * UrlSummaryListItem
         * @description One entry per unique source_url for the home page list.
         */
        UrlSummaryListItem: {
            /** Source Url */
            source_url: string;
            /** Completed Count */
            completed_count: number;
            /** Failed Count */
            failed_count: number;
            /** Pending Count */
            pending_count: number;
            /** Latest Title */
            latest_title: string;
            /**
             * Latest Updated At
             * Format: date-time
             */
            latest_updated_at: string;
        };
        /** UsageMetadata */
        UsageMetadata: {
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Thinking Tokens
             * @default 0
             */
            thinking_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Git Sha */
            git_sha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AiMetrics = components['schemas']['AiMetrics'];
export type AuthStatusResponse = components['schemas']['AuthStatusResponse'];
export type CrossMetrics = components['schemas']['CrossMetrics'];
export type DeepevalItem = components['schemas']['DeepevalItem'];
export type DeepevalPassMetrics = components['schemas']['DeepevalPassMetrics'];
export type DeepevalQueuedResponse = components['schemas']['DeepevalQueuedResponse'];
export type EvaluationRunAggregateMetrics = components['schemas']['EvaluationRunAggregateMetrics'];
export type EvaluationRunCreateRequest = components['schemas']['EvaluationRunCreateRequest'];
export type EvaluationRunCreateResponse = components['schemas']['EvaluationRunCreateResponse'];
export type EvaluationRunDeletedResponse = components['schemas']['EvaluationRunDeletedResponse'];
export type EvaluationRunEntriesResponse = components['schemas']['EvaluationRunEntriesResponse'];
export type EvaluationRunEntryResponse = components['schemas']['EvaluationRunEntryResponse'];
export type EvaluationRunListItemResponse = components['schemas']['EvaluationRunListItemResponse'];
export type EvaluationRunResponse = components['schemas']['EvaluationRunResponse'];
export type EvaluationRunResumeResponse = components['schemas']['EvaluationRunResumeResponse'];
export type EvaluationSetCreateResponse = components['schemas']['EvaluationSetCreateResponse'];
export type EvaluationSetDeletedResponse = components['schemas']['EvaluationSetDeletedResponse'];
export type EvaluationSetDetailResponse = components['schemas']['EvaluationSetDetailResponse'];
export type EvaluationSetEntryImportInput = components['schemas']['EvaluationSetEntryImport-Input'];
export type EvaluationSetEntryImportOutput = components['schemas']['EvaluationSetEntryImport-Output'];
export type EvaluationSetEntryInputTextResponse = components['schemas']['EvaluationSetEntryInputTextResponse'];
export type EvaluationSetEntryResponse = components['schemas']['EvaluationSetEntryResponse'];
export type EvaluationSetExportResponse = components['schemas']['EvaluationSetExportResponse'];
export type EvaluationSetImportRequest = components['schemas']['EvaluationSetImportRequest'];
export type EvaluationSetListItemResponse = components['schemas']['EvaluationSetListItemResponse'];
export type GoldenMetrics = components['schemas']['GoldenMetrics'];
export type GoldenMetricsBackfillResponse = components['schemas']['GoldenMetricsBackfillResponse'];
export type HttpValidationError = components['schemas']['HTTPValidationError'];
export type JobCreateRequest = components['schemas']['JobCreateRequest'];
export type JobCreatedResponse = components['schemas']['JobCreatedResponse'];
export type JobDeletedResponse = components['schemas']['JobDeletedResponse'];
export type JobListItemResponse = components['schemas']['JobListItemResponse'];
export type JobMetrics = components['schemas']['JobMetrics'];
export type JobStatusResponse = components['schemas']['JobStatusResponse'];
export type KeepaliveResponse = components['schemas']['KeepaliveResponse'];
export type KeyTakeawaysMetrics = components['schemas']['KeyTakeawaysMetrics'];
export type PairwiseDeepevalItem = components['schemas']['PairwiseDeepevalItem'];
export type SourceMetrics = components['schemas']['SourceMetrics'];
export type SummaryResponse = components['schemas']['SummaryResponse'];
export type SummaryStatisticalMetrics = components['schemas']['SummaryStatisticalMetrics'];
export type TokenRequest = components['schemas']['TokenRequest'];
export type TokenResponse = components['schemas']['TokenResponse'];
export type UrlSummaryListItem = components['schemas']['UrlSummaryListItem'];
export type UsageMetadata = components['schemas']['UsageMetadata'];
export type ValidationError = components['schemas']['ValidationError'];
export type VersionResponse = components['schemas']['VersionResponse'];
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_auth_status_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusResponse"];
                };
            };
        };
    };
    get_token_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_summarize_job_api_v1_jobs_summarize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_summarized_urls_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlSummaryListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_jobs_flat_api_v1_jobs_list_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: ("pending" | "running" | "completed" | "failed")[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jobs_for_url_api_v1_jobs_by_url_get: {
        parameters: {
            query: {
                /** @description Exact source URL */
                source_url: string;
                /** @description One of supported statuses */
                status: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supported_models_api_v1_meta_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    get_supported_languages_api_v1_meta_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_supported_modes_api_v1_meta_modes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_version_api_v1_meta_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
    keepalive_api_v1_meta_keepalive_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeepaliveResponse"];
                };
            };
        };
    };
    list_evaluation_sets_api_v1_research_evaluation_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSetListItemResponse"][];
                };
            };
        };
    };
    create_evaluation_set_api_v1_research_evaluation_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationSetImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSetCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_set_api_v1_research_evaluation_sets__set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSetDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_evaluation_set_api_v1_research_evaluation_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSetDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_evaluation_set_api_v1_research_evaluation_sets__set_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSetExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_set_entry_input_text_api_v1_research_evaluation_sets__set_id__entries__entry_id__input_text_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
                entry_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSetEntryInputTextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_missing_golden_metrics_api_v1_research_evaluation_sets__set_id__golden_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoldenMetricsBackfillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evaluation_runs_api_v1_research_evaluation_sets__set_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunListItemResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_evaluation_run_api_v1_research_evaluation_sets__set_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_run_api_v1_research_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_evaluation_run_api_v1_research_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunDeletedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evaluation_run_entries_api_v1_research_runs__run_id__entries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunEntriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_run_deepeval_api_v1_research_runs__run_id__deepeval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeepevalQueuedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_evaluation_run_api_v1_research_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationRunResumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
