# .github/workflows/deploy.yml
name: Deploy to GCP

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # wymagane dla OIDC

jobs:
#  changes:
#    outputs:
#      backend: ${{ steps.filter.outputs.backend }}
#      frontend: ${{ steps.filter.outputs.frontend }}
#      infra: ${{ steps.filter.outputs.infra }}
#    steps:
#      - uses: actions/checkout@v4
#      - uses: dorny/paths-filter@v3
#        id: filter
#        with:
#          filters: |
#            backend:
#              - 'backend/**'
#            frontend:
#              - 'frontend/**'
#            infra:
#              - 'infra/terraform/**'

  deploy-backend:
    #needs: changes
    runs-on: ubuntu-latest
    #if: needs.changes.outputs.backend == 'true' || needs.changes.outputs.infra == 'true'
    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REGION: ${{ vars.GCP_REGION }}
      IMAGE: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/app/backend
    outputs:
      vite_api_url: ${{ steps.tf_apply.outputs.vite_api_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}   # projects/NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: ${{ vars.WIF_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build & Push
        run: |
          docker build -t $IMAGE:${{ github.sha }} ./backend
          docker push $IMAGE:${{ github.sha }}

      - uses: hashicorp/setup-terraform@v3
        #with:
          #terraform_version: 1.15.5
          #terraform_wrapper: false

      - name: Terraform Init
        working-directory: infra/terraform/main
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -backend-config="prefix=${{ vars.TF_STATE_PREFIX }}"

      - name: Terraform Apply
        id: tf_apply
        working-directory: infra/terraform/main
        run: |
          terraform apply -auto-approve -var="image_tag=${{ github.sha }}" --var-file=../common.tfvars
          terraform output -raw backend_url
          URL=$(terraform output -raw backend_url)
          echo "vite_api_url=$URL" >> $GITHUB_OUTPUT

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: [deploy-backend]
    #if: |
    #    always() &&
    #    needs.changes.outputs.frontend == 'true' &&
    #    (needs.deploy-backend.result == 'success' || needs.deploy-backend.result == 'skipped')
    env:
      PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      REGION: ${{ vars.GCP_REGION }}
      IMAGE: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/app/frontend

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}   # projects/NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: ${{ vars.WIF_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build
        working-directory: frontend
        run: |
          echo "VITE_API_URL=${{ needs.deploy-backend.outputs.vite_api_url }}" > .env.production
          npm ci
          npm run build

      - name: Configure Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        working-directory: frontend
        run: firebase deploy --only hosting --project ${{ env.PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
